version: '3.8'

services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-youtube-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./sessions:/app/sessions
      - ./logs:/app/logs
      - ./backups:/app/backups
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET:-wallysson-studio-secret-2025}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - CANAL_ID=${CANAL_ID}
    networks:
      - whatsapp-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whatsapp-bot.rule=Host(`bot.seu-dominio.com`)"
      - "traefik.http.routers.whatsapp-bot.tls=true"
      - "traefik.http.routers.whatsapp-bot.tls.certresolver=letsencrypt"

  # Nginx para proxy reverso (opcional)
  nginx:
    image: nginx:alpine
    container_name: whatsapp-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - whatsapp-bot
    networks:
      - whatsapp-network
    profiles:
      - nginx

  # Redis para cache (opcional)
  redis:
    image: redis:alpine
    container_name: whatsapp-redis
    restart: unless-stopped
    volumes:
      - redis-data:/data
    networks:
      - whatsapp-network
    profiles:
      - cache

networks:
  whatsapp-network:
    driver: bridge

volumes:
  redis-data: